export * from "./appointment";
export * from "./department";
export * from "./human-resources";
export * from "./insurance";
export * from "./operation";
export * from "./test";
export * from "./bill";
export * from "./payment";
export * from "./OperationDoctor";
