import {
  emptyDepartment,
  emptyPatient,
  emptyEmployee,
  emptyReceptionist,
  emptyDoctor,
  emptyAdmin,
  emptyTestType,
  emptyTestOrder,
  emptyTestAppointment,
  emptyCountry,
  emptyInsurance,
  emptyOperation,
  emptyPrescription,
  emptyPayment,
  emptyPerson,
} from "./emptyObjects";

export const emptyObjects = {
  Departments: emptyDepartment,
  Patients: emptyPatient,
  Employees: emptyEmployee,
  Receptionists: emptyReceptionist,
  Doctors: emptyDoctor,
  Admins: emptyAdmin,
  TestTypes: emptyTestType,
  TestOrders: emptyTestOrder,
  TestAppointments: emptyTestAppointment,
  Countries: emptyCountry,
  Insurances: emptyInsurance,
  Operations: emptyOperation,
  Prescriptions: emptyPrescription,
  Payments: emptyPayment,
  Persons: emptyPerson,
};
